name = "CMCModels"
uuid = "8a844b39-05e3-4819-8383-f5fae2d66f33"
authors = ["JuliaHub, Inc. and other contributors"]
version = "0.1.0"

[deps]
CedarSim = "9075980a-f0c7-46d2-945a-cc5bead5ad4a"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
VerilogAParser = "b333aca1-b97d-47c9-9908-8e5a8c115e58"

[sources]
CedarSim = {path = "../.."}
VerilogAParser = {path = "../../VerilogAParser.jl"}
