name = "SpectreNetlistParser"
uuid = "72c5b8b4-6eac-4a9c-9647-0f5a982ce801"
authors = ["JuliaHub, Inc. and other contributors"]
version = "0.6.1"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
Lexers = "8fc43420-9e17-4e89-a998-f4e9593a1dfc"
SnoopPrecompile = "66db9d55-30c0-4569-8b51-7e840670fc0c"

[sources]
Lexers = {path = "../Lexers.jl"}

[compat]
AbstractTrees = "0.4"
julia = "1.9"
